USE [master]
GO

/****** Object:  Database [DB_ProjetoMVC]    Script Date: 05/05/2021 21:32:31 ******/
CREATE DATABASE [DB_ProjetoMVC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_ProketoMVC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_ProketoMVC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_ProketoMVC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_ProketoMVC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DB_ProjetoMVC] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_ProjetoMVC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_ProjetoMVC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_ProjetoMVC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_ProjetoMVC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_ProjetoMVC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_ProjetoMVC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_ProjetoMVC] SET  MULTI_USER 
GO

ALTER DATABASE [DB_ProjetoMVC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_ProjetoMVC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_ProjetoMVC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_ProjetoMVC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_ProjetoMVC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_ProjetoMVC] SET QUERY_STORE = OFF
GO

USE [DB_ProjetoMVC]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DB_ProjetoMVC] SET  READ_WRITE 
GO

