//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int id { get; set; }
        public string nome_prod { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<decimal> quantidade { get; set; }
        public Nullable<decimal> preço { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
